name: juggering
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/vopec_logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/aino.jpg
    - assets/images/vopec_icon.png
    - assets/images/DAMN.png
    - assets/images/user.png
    - assets/images/vopec_logo.png
    - assets/images/user_placeholder.png

  fonts:
    - family: SFPRODISPLAYREGULAR
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SF-PRO.ttf
