// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvJYUd-fX1U7u2lLOnC6_CJYUeI0oz7v0',
    appId: '1:4182111236:web:60d2e0b919ef7eb7a2b151',
    messagingSenderId: '4182111236',
    projectId: 'pyropuc',
    authDomain: 'pyropuc.firebaseapp.com',
    storageBucket: 'pyropuc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSCKvSvbZUoTvbMEfzBJpjbQVYVq5Kxm8',
    appId: '1:4182111236:android:aac6f8237d9de80ba2b151',
    messagingSenderId: '4182111236',
    projectId: 'pyropuc',
    storageBucket: 'pyropuc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ZgvQEeIww2eGGjkp4L0ArnFiUqc-CGY',
    appId: '1:4182111236:ios:1bb637c8487280d0a2b151',
    messagingSenderId: '4182111236',
    projectId: 'pyropuc',
    storageBucket: 'pyropuc.firebasestorage.app',
    iosBundleId: 'com.example.juggering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ZgvQEeIww2eGGjkp4L0ArnFiUqc-CGY',
    appId: '1:4182111236:ios:1bb637c8487280d0a2b151',
    messagingSenderId: '4182111236',
    projectId: 'pyropuc',
    storageBucket: 'pyropuc.firebasestorage.app',
    iosBundleId: 'com.example.juggering',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvJYUd-fX1U7u2lLOnC6_CJYUeI0oz7v0',
    appId: '1:4182111236:web:43a6b9a77f75dbc0a2b151',
    messagingSenderId: '4182111236',
    projectId: 'pyropuc',
    authDomain: 'pyropuc.firebaseapp.com',
    storageBucket: 'pyropuc.firebasestorage.app',
  );
}
